### ISSUE TITLE
Sheet insert failures

### ISSUE THREAD

**Issue by Baggerone** [silinternational/app-monitoring-archiver#37]
When more than one new NodePing check name needs to get inserted in the top of the list (rows) of check names in the Google Sheet, one or more can go missing and not actually get inserted or maybe get over-written.

A work around is to manually add new Google Sheer rows in advance for new NodePing checks in the proper place alphabetically.

**Comment by briskt** [comment]
Did you also add this in YouTrack?

**Comment by Baggerone** [comment]
Now I added it to YouTrack.
[ITSE-635](https://itse.youtrack.cloud/issue/ITSE-635) Row insert bug in App Monitoring archiver

**Comment by devon-sil** [comment]
This was fixed already.
